name: forma
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  getwidget: ^6.0.0
  http: ^1.5.0
  ndialog: ^4.4.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  lottie: ^3.1.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

 
  assets:
    - assets/images/

# Flutter Native Splash configuration
flutter_native_splash:
  # Image to display on the splash screen
  image: assets/images/no_background_logo.png
  
  # Color of the image (if it's a monochrome image)
  color: "#FFFFFF"
  
  # Platform-specific configurations
  android_12:
    image: assets/images/no_background_logo.png
    color: "#2563EB"
  
  # iOS configuration
  ios: true
  
  # Web configuration
  web: false

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/forma-logo-png.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false


